Improve 0.6.0 release notes
medic/medic-android pull request #139
Opened 2020-12-01 21:33 UTC by garethbowen

medic/medic-android#137

2020-12-02 01:33 UTC, kennsippell requested changes

2020-12-02 01:41 UTC, garethbowen commented on README.md
> +We are planning improvements to [make the migration more user friendly](https://github.com/medic/medic-android/issues/134) in a future release.
The section you wrote was similar to, but better than, my previous introduction, so I copied it up there.

2020-12-02 01:41 UTC, garethbowen commented
Thanks @kennsippell . Would you mind reviewing the latest version?

2020-12-07 06:56 UTC, dianabarsan approved these changes
👍🏻

2020-12-07 06:56 UTC, dianabarsan commented on README.md
> +Users on Android 9 and below will do not need to be migrated and will be unaffected by this change. Because of this it is recommended that projects upgrade to v0.6.0 version of their app before issui
Typo here `will do not need`

2020-12-15 03:45 UTC, merged

2020-12-15 03:45 UTC, garethbowen commented on README.md
> +Users on Android 9 and below will do not need to be migrated and will be unaffected by this change. Because of this it is recommended that projects upgrade to v0.6.0 version of their app before issui
Fixed.